
arm-complier:
	@echo "Building $(ARM_TOOLS_COMPILER_SOURCE_FILE)"
	arm-none-eabi-gcc $(ARM_TOOLS_COMPILER_MCU_SETTINGS) $(ARM_TOOLS_COMPILER_DEFINES) $(ARM_TOOLS_COMPILER_INCLUDE_PATH) $(ARM_TOOLS_COMPILER_FLAGS) -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(ARM_TOOLS_COMPILER_DEFS_FILE)" -MT"$(ARM_TOOLS_COMPILER_OBJECT_FILE)" -o "$(ARM_TOOLS_COMPILER_OBJECT_FILE)" "$(ARM_TOOLS_COMPILER_SOURCE_FILE)"
	
arm-assembler:
	@echo "Assembling $(ARM_TOOLS_COMPILER_SOURCE_FILE)"
	arm-none-eabi-as $(ARM_TOOLS_COMPILER_MCU_SETTINGS) $(INCLUDE_PATH) -g -o "$(ARM_TOOLS_COMPILER_OBJECT_FILE)" "$(ARM_TOOLS_COMPILER_SOURCE_FILE)"
	
arm-linker:
	@echo "Building target $(ARM_TOOLS_LINKER_TARGET_ELF)"
	arm-none-eabi-gcc $(ARM_TOOLS_COMPILER_MCU_SETTINGS) -T"$(ARM_TOOLS_LINKER_SCRIPT)" -Wl,-Map=$(ARM_TOOLS_LINKER_TARGET_MAP) -Wl,--gc-sections -o "$(ARM_TOOLS_LINKER_TARGET_ELF)" $(ARM_TOOLS_LINKER_OBJECT_FILES) $(ARM_TOOL_LINKER_LIBRARIES) $(ARM_TOOL_LINKER_OPTIONS)