/*
 * ADC.h
 */

#ifndef ADC_H_
#define ADC_H_

#include <stdint.h>

#define ADC_TO_PIN_VOLTAGE (3.3/4095)

typedef enum
{
	ADC_CHANNEL_ADC_BAT0_1,
	ADC_CHANNEL_ADC_BAT0_2,
	ADC_CHANNEL_ADC_BAT0_3,
	ADC_CHANNEL_ADC_BAT0_4,
	ADC_CHANNEL_ADC_BAT0_5,
	ADC_CHANNEL_ADC_BAT0_6,
	ADC_CHANNEL_ADC_BAT1_1,
	ADC_CHANNEL_ADC_BAT1_2,
	ADC_CHANNEL_ADC_BAT1_3,
	ADC_CHANNEL_ADC_BAT1_4,
	ADC_CHANNEL_ADC_BAT1_5,
	ADC_CHANNEL_ADC_BAT1_6,
	ADC_CHANNEL_ADC_EXT_PRESSURE,
	ADC_CHANNEL_ADC_WATER_SENSE,
    
    ADC_CHANNEL_COUNT,
} ADC_channel_E;

void ADC_init(void);
uint16_t ADC_getChannelData(const ADC_channel_E channel);

#endif /* ADC_H_ */
