/*
 * ADC.h
 */

#ifndef POWERBOARD1_CODE_APP_ADC_H_
#define POWERBOARD1_CODE_APP_ADC_H_

#include <stdint.h>

typedef enum
{
	ADC_CHANNEL_ADC_BAT0_1,
	ADC_CHANNEL_ADC_BAT0_2,
	ADC_CHANNEL_ADC_BAT0_3,
	ADC_CHANNEL_ADC_BAT0_4,
	ADC_CHANNEL_ADC_BAT0_5,
	ADC_CHANNEL_ADC_BAT0_6,
	ADC_CHANNEL_ADC_BAT1_1,
	ADC_CHANNEL_ADC_BAT1_2,
	ADC_CHANNEL_ADC_BAT1_3,
	ADC_CHANNEL_ADC_BAT1_4,
	ADC_CHANNEL_ADC_BAT1_5,
	ADC_CHANNEL_ADC_BAT1_6,
	ADC_CHANNEL_ADC_EXT_PRESSURE,
    
    ADC_CHANNEL_COUNT,
} ADC_channel_E;

void ADC_init(void);
uint16_t ADC_getChannelData(const ADC_channel_E channel);

#endif /* POWERBOARD1_CODE_APP_ADC_H_ */
