
OUTPUT_DIR=PB_TEST
TEST_CODE_DIR=code
CODE_DIR=code
SHARED_CODE_DIR=$(REPO_ROOT)/shared/code

-include first_pb_test.mk

test:
	$(MAKE) first_pb_test

clean:
	rm -rf $(OUTPUT_DIR)

#-include $(TEST_C_DEPS)
