
OUTPUT_DIR=MC_TEST
TEST_CODE_DIR=code
CODE_DIR=code
SHARED_CODE_DIR=$(REPO_ROOT)/shared/code

-include first_mc_test.mk

test:
	$(MAKE) first_mc_test

clean:
	rm -rf $(OUTPUT_DIR)

#-include $(TEST_C_DEPS)
