/*
 * circBuffer2D_componentSpecific.h
 *
 *  Created on: Jul 22, 2019
 *      Author: Poornachander
 */

#ifndef MOTORCONTROLLER2_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_
#define MOTORCONTROLLER2_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_

typedef enum
{
	CIRCBUFFER2D_CHANNEL_UART_RX,

	CIRCBUFFER2D_CHANNEL_COUNT
} circBuffer2D_channel_E;



#endif /* MOTORCONTROLLER2_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_ */
