/*
 * circBuffer2D_componentSpecific.h
 *
 *  Created on: Jul 22, 2019
 *      Author: Poornachander
 */

#ifndef POWERBOARD1_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_
#define POWERBOARD1_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_

typedef enum
{
	CIRCBUFFER2D_CHANNEL_UART_TX,

	CIRCBUFFER2D_CHANNEL_COUNT
} circBuffer2D_channel_E;



#endif /* POWERBOARD1_CODE_APP_CIRCBUFFER2D_COMPONENTSPECIFIC_H_ */
