/*
 * messageHandler_componentSpecific.h
 *
 *  Created on: Feb 9, 2020
 *      Author: Poorna Chander Kalidas
 */

#ifndef POWERBOARD1_CODE_APP_MESSAGEHANDLER_COMPONENTSPECIFIC_H_
#define POWERBOARD1_CODE_APP_MESSAGEHANDLER_COMPONENTSPECIFIC_H_

typedef enum
{
    MESSAGE_HANDLER_RX_MESSAGE_CHANNEL_POWER_ENABLE,
    MESSAGE_HANDLER_RX_MESSAGE_CHANNEL_POLARIS_REQUEST,

    MESSAGE_HANDLER_RX_MESSAGE_CHANNEL_COUNT,

} messageHandler_RXMessageChannel_E;

typedef enum
{
    MESSAGE_HANDLER_TX_MESSAGE_CHANNEL_RID,
    MESSAGE_HANDLER_TX_MESSAGE_CHANNEL_ENV_DATA,

    MESSAGE_HANDLER_TX_MESSAGE_CHANNEL_COUNT,
} messageHandler_TXMessageChannel_E;


#endif /* POWERBOARD1_CODE_APP_MESSAGEHANDLER_COMPONENTSPECIFIC_H_ */
