/*
 * UART_componentSpecific.h
 *
 *  Created on: Jul 23, 2019
 *      Author: Poornachander
 */

#ifndef POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_
#define POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_

#endif /* POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_ */
