/*
 * UART_componentSpecific.h
 *
 *  Created on: Jul 23, 2019
 *      Author: Poornachander
 */

#ifndef POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_
#define POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_

#define UART_TX_BUFFER_SIZE	(64U)

#define UART_RX_BUFFER_LENGTH (36U)
#define UART_RX_BUFFER_COUNT  (8U)

#endif /* POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_ */
