/*
 * UART_componentSpecific.h
 *
 *  Created on: Jul 23, 2019
 *      Author: Poornachander
 */

#ifndef POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_
#define POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_

#include "UARTProtocol.h"

#define UART_TX_BUFFER_LENGTH  (UART_PROTOCOL_MAX_PAYLOAD_SIZE)
#define UART_TX_BUFFER_COUNT   (8U)

#endif /* POWERBOARD1_CODE_APP_UART_COMPONENTSPECIFIC_H_ */
